const CONFIG = {
  API_SERVER_URL: process.env.REACT_APP_API_SERVER_URL,
  CLIENT_URL: process.env.REACT_APP_CLIENT_URL,
  SAMPLE_ORIGINAL_FILE_URL: process.env.REACT_APP_SAMPLE_ORIGINAL_FILE_URL,
  SAMPLE_COMPARABLE_FILE_URL: process.env.REACT_APP_SAMPLE_COMPARABLE_FILE_URL,
  EXPLAIN_YOUTUBE_URL: "https://www.youtube.com/embed/37LBz-SKdxM",
};

export default CONFIG;
