const PAGE_SEQUENCES = {
  FILE_NOT_ADDED: "PAGE_SEQUENCES/FILE_NOT_ADDED",
  ORIGINAL_FILE_ADDED: "PAGE_SEQUENCES/ORIGINAL_FILE_ADDED",
  COMPARABLE_FILE_ADDED: "PAGE_SEQUENCES/COMPARABLE_FILE_ADDED",
  COMPARE_FILES: "PAGE_SEQUENCES/COMPARE_FILES",
  PREVIEW: "PAGE_SEQUENCES/PREVIEW",
  ERROR: "PAGE_SEQUENCES/ERROR",
};

export default PAGE_SEQUENCES;
