const PPT_DATA_TYPES = {
  ORIGINAL_PPT_DATA: "PPT_DATA_TYPES/ORIGINAL_PPT_DATA",
  COMPARABLE_PPT_DATA: "PPT_DATA_TYPES/COMPARABLE_PPT_DATA",
  MERGED_PPT_DATA: "PPT_DATA_TYPES/MERGED_PPT_DATA",
};

export default PPT_DATA_TYPES;
