const SEQUENCES = {
  INITIAL_SEQUENCE: "SEQUENCES/INITIAL_SEQUENCE",
  ADDED_ORIGINAL_FILE: "SEQUENCES/ADDED_ORIGINAL_FILE",
  ADDED_COMPARABLE_FILE: "SEQUENCES/ADDED_COMPARABLE_FILE",
  COMPARISION: "SEQUENCES/COMPARISION",
  PREVIEW: "SEQUENCES/PREVIEW",
};

export const SEQUENCE_FLOW = [
  SEQUENCES.INITIAL_SEQUENCE,
  SEQUENCES.ADDED_ORIGINAL_FILE,
  SEQUENCES.ADDED_COMPARABLE_FILE,
  SEQUENCES.COMPARISION,
  SEQUENCES.PREVIEW,
];

export default SEQUENCES;
