const SEQUENCES = {
  INITIAL_SEQUENCE: "SEQUENCES/INITIAL_SEQUENCE",
  ADDED_ORIGINAL_FILE: "SEQUENCES/ADDED_ORIGINAL_FILE",
  ADDED_COMPARABLE_FILE: "SEQUENCES/ADDED_COMPARABLE_FILE",
  COMPARISION: "SEQUENCES/COMPARISION",
  DOWNLOAD: "SEQUENCES/DOWNLOAD",
};

export const SEQUENCE_FLOW = [
  SEQUENCES.INITIAL_SEQUENCE,
  SEQUENCES.ADDED_ORIGINAL_FILE,
  SEQUENCES.ADDED_COMPARABLE_FILE,
  SEQUENCES.COMPARISION,
  SEQUENCES.DOWNLOAD,
];

export default SEQUENCES;
