const THEME_COLORS = {
  MAIN_COLOR: "#FD6347",
  FONT_COLOR: "#463f49",
  MAIN_BACKGROUND: "#FFFFFF",
  SECTION_BACKGROUND: "#F1F3F6",
  SLIDE_BACKGROUND: "#FFFFFF",
  HIGHLIGHT_HOVERED: "#FFCB77",
  HIGHLIGHT_ADDED: "#74C991",
  HIGHLIGHT_DELETED: "#FE6D73",
  MODAL_BACKGROUND: "rgba(0, 0, 0, 0.55)",
  MODAL_COLOR: "#FFFFFF",
};

export default THEME_COLORS;
