const THEME_COLORS = {
  FONT_COLOR: "#FFF",
  BACKGROUND_COLOR: "#1E1E1E",
  HIGHLIGHT_HOVERED: "#F7F700",
  HIGHLIGHT_ADDED: "#74C991",
  HIGHLIGHT_DELETED: "#F14C4C",
};

export default THEME_COLORS;
